spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mockito
    username: root
    password: root12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5InnoDialect